#cloud-config
users:
  - default
  - name: ubuntu
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCZEriDm4fDkMFXfeefHDjd52Wv4SBikOvu5PG46fEWC+34jvhxaR0fZsHXoiCSENieGALPj19RpZ01fVpE2uGMSKIVmhyzLJSxtfzD0zd5V85kVHYUJgIHOdnyhLmVxySueeUzPcR0DNC4Ev7yuvIhza7Ot857K22GGNA658RnT1m9DCjwWPaJZ5P6QrZjFIGG71YWhmcr7zETM3Hu7CePgBE6lSzrj1AyemuGZDWJpPKM0V/dB9EM+xEoumvS/NJkSFveNTwDLSkPBjlq7BXlaiJx4MCX+cDt+mCZlm6t3e7Bsb5x2H/0P4rmhtf8M9qdsm1LUIlrFvBAWfRB+ud ferdi@DESKTOP-HFA54P3
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCpxUnP8vCro31Xt2EcSKc/qB+0S/32UudZOUbyySZveVStUD6TJ4+ZaqYFsdCYLjGHXyo7jyUuwgKMrtP14dHr71easmnhyxeDqNunN2nQMSoph2emspP6lZrH6w+XmWTsau7tSSh8y78Jeq0ebrt0gzGWGBQITxT3MsZ8WR+f1tYrkASNJyYckrbSB3vK34w+LTbsjSa52CVkXCAzbFf6oR/or9luVU9pdj/TnX+OXsMgcSpYeH8o5rAlyBhOFIio5wNXXYZlaBcKOs29xB4oWXjlKRwlz592TIYBIjHHJkXf3kJfZmy+y94aHCs/Ih9QROzR0VFGmxeTPRM+Kf1GbnB8+HyqRWNVpsnvZlPqikfIVU9dyGm1CcpPgwX+/BYs661PMfAZjqgR50Pte1nR+nq0TCQFHp/06px92fXuBVUO6/nl1lPCZqMGcT1jb7OTXk3NpqYnphaUNWhhRrSk7xmi/muYm+jzgZtabptXM2741fLo8QSLodSPrgy2CPE= ferdi@LAPTOP-S6G27617
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash

package_update: true

packages:
 - runc

runcmd:
- curl -sLSf https://github.com/containerd/containerd/releases/download/v1.3.2/containerd-1.3.2.linux-amd64.tar.gz > /tmp/containerd.tar.gz && tar -xvf /tmp/containerd.tar.gz -C /usr/local/bin/ --strip-components=1
- curl -SLfs https://raw.githubusercontent.com/containerd/containerd/v1.3.2/containerd.service | tee /etc/systemd/system/containerd.service
- systemctl daemon-reload && systemctl start containerd
- systemctl enable containerd
- /sbin/sysctl -w net.ipv4.conf.all.forwarding=1
- mkdir -p /opt/cni/bin
- curl -sSL https://github.com/containernetworking/plugins/releases/download/v0.8.5/cni-plugins-linux-amd64-v0.8.5.tgz | tar -xz -C /opt/cni/bin
- mkdir -p /go/src/github.com/openfaas/
- cd /go/src/github.com/openfaas/ && git clone https://github.com/openfaas/faasd
- curl -fSLs "https://github.com/openfaas/faasd/releases/download/0.8.2/faasd" --output "/usr/local/bin/faasd" && chmod a+x "/usr/local/bin/faasd"
- cd /go/src/github.com/openfaas/faasd/ && /usr/local/bin/faasd install
- systemctl status -l containerd --no-pager
- journalctl -u faasd-provider --no-pager
- systemctl status -l faasd-provider --no-pager
- systemctl status -l faasd --no-pager
- curl -sSLf https://cli.openfaas.com | sh
- sleep 5 && journalctl -u faasd --no-pager
- cat /var/lib/faasd/secrets/basic-auth-password | /usr/local/bin/faas-cli login --password-stdin